### PR TITLE
cherrypy metrics server blocking startup

### PR DESCRIPTION
**Pull request by jcpunk**
This should fix the startup blocking issue with cherrypy and add it to the testing framework.

It about doubles the testing time on my system, so I added some more workers to pytest-xdist to try and offset the cost.

### CODE REVIEW

**Review by mambelli — COMMENTED** [review]
Hi Pat,
you postponed the startup of the monitoring server. Shouldn't it be started before the channels (maybe still in _start_de_server())?

**Comment by jcpunk** [comment]
Moved to be earlier, I'd love some thoughts from @shreyb too

**Comment by mambelli** [comment]
@jcpunk unit tests failed now. Maybe was an intermittent error (crashing the runner?). Can you check or refresh the PR to restart the tests?

**Comment by shreyb** [comment]
> Moved to be earlier, I'd love some thoughts from @shreyb too

I agree with Marco that ideally we'd start the metrics server first, since then we could monitor the starting up of channels and not just their status after they had already started.  That being said, if it's causing issues to have the webserver start first, I'm fine with it being last.

As far as the unit tests failing, I did notice that starting the webserver in the unit tests caused the tests to hang (and then fail), but NOT when I actually ran the DE outside the scope of unit tests.  For that reason, in the commit https://github.com/HEPCloud/decisionengine/commit/a409f12654d9301784b8cdc813c25a0cd7efaab7, I set the default in the test fixtures to not have the webserver start up.

**Review by mambelli — APPROVED** [review]
Approved. With the note from @shreyb that we may have to do something to fix the unit tests

**Pull request merged**
