### PR TITLE
Add instructions for running the Redis container.

### PR DESCRIPTION
**Pull request by jcpunk**

### CODE REVIEW

**Comment by mambelli** [comment]
@jcpunk Do you know if this will be OK to run on fermicloud or if we'll need a license or alternative to the docker command starting January?

**Comment by jcpunk** [comment]
Hmm, I forgot about the license change.

I've switched the doc to reference `podman` which is a dropin replacement for `docker` in most cases.

**Comment by mambelli** [comment]
@jcpunk, did anything change in the code in the last push? Strangely it shows the same errors in the unit tests that Lisa is having, and the previous one was OK.

**Comment by jcpunk** [comment]
I believe these errors are fixed in https://github.com/HEPCloud/decisionengine/pull/555

**Review by mambelli — APPROVED** [review]

**Pull request merged**
